### ISSUE TITLE
Configurable Native Library Names

### ISSUE THREAD

**Issue by webfolderio** [jwharm/java-gi-generated-sources#2]
I can successfully run the HelloWorld.java example with minor changes on Windows 10 platform.
With help of [gvsbuild](https://github.com/wingtk/gvsbuild) project, it's very easy to compile Gtk with VS 2022.
The only problem is, gvsbuild adds **-0** suffix to file names.
Instead of glib-2.0.dll gvsbuild produces glib-2.0-0.dll.
I did the necessary changes to add that prefix (e.g. `System.loadLibrary("glib-2.0") -> System.loadLibrary("glib-2.0-0")`)

It might be good idea to add an option to configure library names.
I am not sure if gvsbuild an option to configure to remove prefix but for the both case configurable library names might be a nice to have feature.

**Comment by jwharm** [comment]
The -0 suffix is a library version number, comparable to ".so.0" on Linux. You can let `libtool` omit the version with the `-avoid-version` parameter, but I don't know how you would do that in gvsbuild, and it would probably be against best practices anyway.

To solve the issue, you can configure the library names in the `gtk4/build.gradle.ks` script in the `java-gi` repository and then generate the jar with `gradle build`. (The `java-gtk4` repository is just a copy of the intermediate generated sources.) 

(The bindings generator needs the gobject-introspection (gir) files, which `gvsbuild` will create with the `enable_gi` option. You can specify the location of the gir files in the same `gtk4/build.gradle.ks` file mentioned above.)

It's probably possible to create platform-specific build scripts so you don't have to change the build file, but I don't know enough about Gradle to do this by myself.

Please log an issue in the java-gi repository if you encounter any problems running the java-gi tool.

**Comment by jwharm** [comment]
By the way, there is at least one bug that I know about, that will occur specifically on Windows. GLib's `glong` values, which are C typedefs for `long`, are marshalled to Java `long` values, but that is incorrect on Wndows. Linux and Java `long` are 64-bit, Windows `long` is 32-bit. So whenever you use a GTK function with `long` parameters, or a GTK struct with `long` fields, you can expect issues.

**Comment by jwharm** [comment]
A new issue has been opened in the java-gi repository ([#16](https://github.com/jwharm/java-gi/issues/16)).
